/*
 * File: app/view/contactPicture.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.contactPicture', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer3',

    config: {
        height: 100,
        id: 'contactPicture',
        minHeight: 100,
        style: 'overflow: hidden',
        ui: '',
        layout: {
            align: 'end',
            pack: 'end',
            type: 'vbox'
        },
        overflow: 'hidden',
        items: [
            {
                xtype: 'component',
                html: '<img src="">',
                style: 'background-image:url(\'http://www.miltonblack.com.au/images/Star%20Club/man.jpg\')'
            },
            {
                xtype: 'button',
                id: 'pictureButton',
                iconCls: 'add',
                iconMask: true,
                text: ''
            }
        ]
    }

});