/*
 * File: app/view/ContactForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ContactForm', {
    extend: 'Ext.Container',
    requires: [
        'MyApp.view.ContactPicture'
    ],

    config: {
        id: 'contactInfo',
        padding: '10px',
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        id: 'starContact',
                        ui: 'decline',
                        iconMask: true,
                        text: 'Cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'editContact',
                        ui: 'action',
                        iconCls: '',
                        iconMask: true,
                        text: 'Save'
                    }
                ]
            },
            {
                xtype: 'contactpic'
            },
            {
                xtype: 'textfield',
                itemId: 'firstName',
                margin: '10px 0 0 0',
                label: 'First Name',
                labelAlign: 'top',
                name: 'firstName',
                readOnly: false
            },
            {
                xtype: 'textfield',
                itemId: 'lastName',
                label: 'Last Name',
                labelAlign: 'top',
                name: 'lastName',
                readOnly: false
            },
            {
                xtype: 'textfield',
                itemId: 'phoneNumber',
                label: 'Phone Number',
                labelAlign: 'top',
                name: 'phoneNumber',
                readOnly: false
            },
            {
                xtype: 'emailfield',
                itemId: 'emailAddress',
                label: 'Email Address',
                labelAlign: 'top',
                name: 'emailAddress',
                placeHolder: 'email@example.com',
                readOnly: false
            },
            {
                xtype: 'textfield',
                itemId: 'address',
                label: 'Address',
                labelAlign: 'top',
                name: 'address',
                readOnly: false
            },
            {
                xtype: 'textfield',
                itemId: 'city',
                label: 'City',
                labelAlign: 'top',
                name: 'city',
                readOnly: false
            },
            {
                xtype: 'textfield',
                id: 'state',
                itemId: 'address',
                label: 'State',
                labelAlign: 'top',
                name: 'city',
                readOnly: false
            },
            {
                xtype: 'numberfield',
                id: 'zipcode',
                itemId: 'address',
                label: 'Zipcode',
                labelAlign: 'top',
                name: 'zipcode',
                readOnly: false
            }
        ]
    }

});