/*
 * File: app/view/ContactInfo.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ContactInfo', {
    extend: 'Ext.Container',
    requires: [
        'MyApp.view.ContactPicture'
    ],

    config: {
        id: 'contactInfo',
        padding: '10px',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'component',
                        html: 'First Name Last Name',
                        id: 'nameBack',
                        flex: 3
                    },
                    {
                        xtype: 'button',
                        id: 'starContact',
                        iconCls: 'favorites',
                        iconMask: true,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        id: 'editContact',
                        iconCls: 'compose',
                        iconMask: true,
                        text: ''
                    }
                ]
            },
            {
                xtype: 'contactpic'
            },
            {
                xtype: 'textfield',
                disabled: true,
                itemId: 'emailAddress',
                clearIcon: false,
                label: 'Email Address',
                labelAlign: 'top',
                name: 'emailAddress',
                readOnly: true
            },
            {
                xtype: 'textfield',
                disabled: true,
                itemId: 'phoneNumber',
                clearIcon: false,
                label: 'Phone Number',
                labelAlign: 'top',
                name: 'phoneNumber',
                readOnly: true
            },
            {
                xtype: 'textfield',
                disabled: true,
                id: 'address',
                clearIcon: false,
                label: 'Address',
                labelAlign: 'top',
                name: 'address',
                readOnly: true
            }
        ]
    }

});