/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                title: 'Groups'
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                title: 'Contacts',
                items: [
                    {
                        xtype: 'list',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ],
                        grouped: true,
                        indexBar: true
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                title: 'Favorites',
                items: [
                    {
                        xtype: 'dataview',
                        itemTpl: [
                            '<div>Data View Item {string}</div>'
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'top',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        }
    }

});