/*
 * File: app/model/Contact.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.model.Contact', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'firstName',
                type: 'string'
            },
            {
                name: 'lastName',
                type: 'string'
            },
            {
                name: 'phoneNumber',
                type: 'string'
            },
            {
                name: 'emailAddress',
                type: 'string'
            },
            {
                name: 'address',
                type: 'string'
            },
            {
                name: 'city',
                type: 'string'
            },
            {
                name: 'state',
                type: 'string'
            },
            {
                name: 'zipcode',
                type: 'string'
            },
            {
                name: 'picture',
                defaultValue: 'resources/img/defaultContactPic.png'
            },
            {
                name: 'isFavorite',
                type: 'boolean'
            }
        ]
    }
});