/*
 * File: app/controller/Contacts.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.controller.Contacts', {
    extend: 'Ext.app.Controller',
    config: {
        stores: [
            'ContactStore'
        ],

        refs: {
            contactinfo: {
                selector: 'contactinfo',
                xtype: 'contactinfo',
                autoCreate: true
            },
            contactform: {
                selector: 'contactform',
                xtype: 'contactform',
                autoCreate: true
            },
            contactlist: {
                selector: 'contactlist',
                xtype: 'contactlist',
                autoCreate: true
            }
        },

        control: {
            "button#addContactBtn": {
                tap: 'onAddContactBtnTap'
            },
            "button#addGroupBtn": {
                tap: 'onAddGroupBtnTap'
            },
            "button#saveContactBtn": {
                tap: 'onSaveContactBtnTap'
            },
            "button#editContactBtn": {
                tap: 'onEditContactBtnTap'
            },
            "button#cancelBtn": {
                tap: 'onCancelBtnTap'
            },
            "button#infoBackBtn": {
                tap: 'onInfoBackBtnTap'
            },
            "dataview": {
                itemtap: 'onContactListTap'
            },
            "favoriteview": {
                activate: 'onFavoriteViewActivate'
            },
            "list": {
                activate: 'onListActivate'
            },
            "contactpic": {
                change: 'onContactPickerChange'
            }
        }
    },

    onAddContactBtnTap: function(button, e, options) {
        var referrer = Ext.Viewport.getActiveItem();
        var form = this.getContactform();
        form.setRecord(null);
        form.reset();
        form.referrer = referrer;
        Ext.Viewport.setActiveItem(form);
    },

    onAddGroupBtnTap: function(button, e, options) {
        Ext.Msg.prompt('Add Group',
        'Enter the group name:',
        function (button, name) {
            if (button === 'ok') {
                var cc = Contact.app.getController('Contacts');

                if (!cc.groupExists(name)) {
                    var gs = Ext.StoreMgr.lookup('GroupStore');

                    gs.add({name:name});

                    console.log('Saved '+name+' group');
                }
                else {
                    Ext.Msg.alert(name+' group exists', 'Please enter a different name');
                }

            }
        });
    },

    onSaveContactBtnTap: function(button, e, options) {
        var form = this.getContactform();
        var errors = form.getValidationErrors();

        if (errors.length) {
            Ext.Msg.alert('Error', errors.join('<br/>'));
        } else {
            var values = form.getValues();
            var record = form.getRecord();
            if (record) {
                record.setData(values);
                record.commit();
                if (form.referrer.setInfo) {
                    form.referrer.setInfo(record);
                }
            } else {
                Ext.StoreManager.lookup('ContactStore').add(values);
            }
            Ext.Viewport.setActiveItem(form.referrer);
            delete form.referrer;
        }

    },

    onEditContactBtnTap: function(button, e, options) {
        var referrer = Ext.Viewport.getActiveItem();
        var form = this.getContactform();
        var info = this.getContactinfo();
        form.referrer = referrer;
        Ext.Viewport.setActiveItem(form);
        form.setRecord(info.getRecord());
    },

    onCancelBtnTap: function(button, e, options) {
        var form = this.getContactform();
        Ext.Viewport.setActiveItem(form.referrer);
        delete form.referrer;

    },

    onInfoBackBtnTap: function(button, e, options) {
        Ext.Viewport.setActiveItem(0);
    },

    onContactListTap: function(dataview, index, target, record, e, options) {
        var active = dataview.getItemId();

        var items = ['ContactList', 'FavoriteView'];

        if (active in this.allowed(items)) {
            var info = this.getContactinfo();
            info.setRecord(record);
            Ext.Viewport.setActiveItem(info);
            console.log('Item tap on '+active);
        }
    },

    onFavoriteViewActivate: function(container, newActiveItem, oldActiveItem, options) {
        var ds = Ext.StoreManager.lookup('ContactStore');
        ds.filter('isFavorite', true);
    },

    onListActivate: function(container, newActiveItem, oldActiveItem, options) {
        var ds = Ext.StoreManager.lookup('ContactStore');
        ds.clearFilter();
    },

    onContactPickerChange: function(picker, value, options) {
        var currentForm = Ext.Viewport.getActiveItem();
        var record = currentForm.getRecord();
        if (record) {
            Ext.Msg.alert('pic', 'setting pic to ' + value);
            record.set('picture', value);
            record.commit();
            currentForm.setRecord(record);
        }

    },

    groupExists: function(name) {
        var gs = Ext.StoreMgr.lookup('GroupStore');

        return gs.findRecord('name', name, 0, true);
    },

    allowed: function(items) {
        var o = {};
        for(var i=0;i<items.length;i++)
        {
            o[items[i]]='';
        }
        return o;
    }

});